[Feature/Bar-145] 로그인 구현
YAPP-Github/23rd-Web-Team-2-FE pull request #48
Opened 2024-01-28 15:57 UTC by dongkyun-dev

## Summary

## To Reviewers

af04ed416c1361791ae7c463c0bdd82270d228d9
alias 설정을 바꿔보았습니다. 덕분에 코드가 깔끔해졌고 추가적으로 생기는 폴더에 대한 대응이 쉬워졌는데, 자동완성이 안되는 큰 문제가 있습니다.

21d2ba1d062283f0412aa077c469d97b72d0711e
로그인을 하지 않은 사용자의 경우 intro 페이지로 이동, 로그인을 통한 토큰 세팅까지 작업한 상태입니다. 토큰 만료 처리나 새로고침을 통한 토큰 재발급에 대한 부분은 별도 PR에서 작성하겠습니다.

3d67c11d42a78493810ca2952048c85ab3ee448e
`type`에 대한 파일들은 `src/customTypes` 하위에 몰면 어떨까 싶습니다. 찾아보니 `@types` 라는 이름은 `node_modules/@types`를 위해 지정된 이름이기 때문에 사용이 불가하다고 합니다. 만약 괜찮다면 해당 PR에서 `src/api/spell/types/index.ts`에 있는 내용을 customTypes 하위로 이동시킬까 합니다.

6e5bd600534e8edb0108bedbdcf06bb2a2b2bf1a
`queries` 폴더 하위에 feature에 대한 파일을 만들고 그 안에 관련된 쿼리 훅들을 한번에 작성하면 어떨까요? 각 쿼리 훅을 개별로 작성하게 되면 파일이 불필요하게 너무 많아지고 구분이 힘들어질 것 같다는 생각이 들었습니다.

피그마에서 svg로 가져왔을 때 코드의 길이가 심하게 긴 아이콘들이 있습니다. (구글, 카카오, 인스타그램) 이러한 아이콘들은 png 파일로 가져올까 하는데 어떨까요?

`.env.local` 파일에 일단 특별한 내용이 없어서 ignore에 추가하지 않았습니다.

## How To Test

- 스토리북 정상 동작 확인
- 토큰이 없는 경우 intro 페이지 이동 확인
- 카카오 로그인 완료 이후 끄적이는 페이지 이동 확인

2024-01-29 06:24 UTC, dmswl98 reviewed
수고하셨습니다!! 
env 내용은 숨겨야 하지 않을까요....?

2024-01-29 06:24 UTC, dmswl98 commented on src/components/Modal/modals/Login.tsx
> +
모달(컴포넌트) 내부에 auth와 관련된 로직을 작성하기 보다 useAuth 훅을 생성해 내부에서 모든 로직을 처리하면 어떨까요?
그럼 모든 곳에서 일관성있게 코드를 작성할 수 있을 것 같아요.

```tsx
const useAuth = () => {
  return {
    isAuth,
    login,
    logout,
  };
}

const LoginModal = () => {
   const { login } = useAuth();

   return  <Button onClick={login('google')} />
}
```

2024-01-29 06:24 UTC, dmswl98 commented on src/stores/token.ts
> +}
토큰을 클라이언트 상태로 저장하는 이유가 무엇인가요??

2024-01-30 07:54 UTC, wonjin-dev reviewed
| type에 대한 파일들은 src/customTypes 하위에 몰면 어떨까 싶습니다. 찾아보니 @types 라는 이름은 node_modules/@types를 위해 지정된 이름이기 때문에 사용이 불가하다고 합니다. 만약 괜찮다면 해당 PR에서 src/api/spell/types/index.ts에 있는 내용을 customTypes 하위로 이동시킬까 합니다.

해당 부분에 대한 상세한 설명이 필요할것 같습니다

2024-01-30 07:55 UTC, wonjin-dev commented on tsconfig.json
> alias 설정을 바꿔보았습니다. 덕분에 코드가 깔끔해졌고 추가적으로 생기는 폴더에 대한 대응이 쉬워졌는데, 자동완성이 안되는 큰 문제가 있습니다.

여기에 설정을 안해서로 추정되는데, 지우신 이유가 따로 있나요 ?

2024-01-30 07:57 UTC, wonjin-dev reviewed
svg를 png로 export해서 혼용하는 것에 대해서는 이견이 없지만, 해당 사유가 LOC라면 조금 의문입니다 !
우리 프로젝트에서 svg파일은 리액트 FC로 단언해서 사용하고 있는데 LOC와 svg 비사용의 관계를 어떻게 정의하신걸까용 ?

2024-01-30 08:00 UTC, wonjin-dev requested changes
queries폴더가 src에 나오는것 보다는 domain 안에 auth라는 폴더를 만들어지고 api와 queries를 만들기로 한 것이 컨벤션으로 기억합니다

2024-01-31 11:49 UTC, dongkyun-dev commented on src/api/http.ts
> +  ): Promise<ResponseType> => instance.post(url, param, options),
이전 PR에서 `response.data`를 반환하는 형태로 변경되어서 `AxiosResponse`로 감쌀 필요가 없어보여서 제거했습니다!

2024-01-31 13:51 UTC, dongkyun-dev commented on src/stores/token.ts
> +}
@wonjin-dev @dmswl98 
해당 부분에 대한 처리로 고민했던 2가지 방법이 있었습니다.

1. `/redirect/[authType]/index.tsx` 파일 생성 => 이곳에서 token을 받아오는 api를 호출 => /write 페이지로 리다이렉트
2. 현재 방법

1번 방법에서의 문제는 불필요한 페이지를 만들어야 한다는 점, write 페이지로 router.push를 했을 때 CSS 파일이 불러와지지 않는 다는 문제가 있었습니다. 아직 왜 CSS 파일이 적용되지 않았는지에 대해서는 정확히 모르겠습니다....

때문에 현재의 방법을 사용했는데, 현재 방법의 단점은 middleware에서 axios를 사용하지 못한다는 점이 있습니다. axios를 사용하지 못하다보니 현재 구조가 됐는데... 혹시 요런 문제들을 해결할 수 있는 좋은 방법이 있을까요?

2024-01-31 13:54 UTC, dongkyun-dev commented
> svg를 png로 export해서 혼용하는 것에 대해서는 이견이 없지만, 해당 사유가 LOC라면 조금 의문입니다 ! 우리 프로젝트에서 svg파일은 리액트 FC로 단언해서 사용하고 있는데 LOC와 svg 비사용의 관계를 어떻게 정의하신걸까용 ?

[BABEL] Note: The code generator has deoptimised the styling of /Users/miro/Desktop/yapp-23rd/src/assets/icons/instagram.svg as it exceeds the max of 500KB.
말씀드린 svg 파일들 자체가 너무 크다보니 이런 에러가 발생해서... 이런 에러를 발생시키는 파일들에 한해서만 png로 변경할까 생각했습니다!

2024-01-31 14:01 UTC, dongkyun-dev commented on src/components/Modal/modals/Login.tsx
> +
@dmswl98 
좋네요!! 이 부분은 추후 PR에 auth 관련한 다른 기능들을 추가할 때 처리해보겠습니다

2024-01-31 14:13 UTC, dongkyun-dev commented
> > type에 대한 파일들은 src/customTypes 하위에 몰면 어떨까 싶습니다. 찾아보니 @types 라는 이름은 node_modules/@types를 위해 지정된 이름이기 때문에 사용이 불가하다고 합니다. 만약 괜찮다면 해당 PR에서 src/api/spell/types/index.ts에 있는 내용을 customTypes 하위로 이동시킬까 합니다.
> 
> 해당 부분에 대한 상세한 설명이 필요할것 같습니다

@wonjin-dev 
공통 로직의 type을 분리하고 싶은데 이를 정의할 폴더가 필요합니다. src 하위에 types 라는 폴더를 만들게 되면 절대경로상으로 @types가 되고 이렇게 사용하는 경우 문제가 발생하더라고요...! (저희의 types 폴더를 잡는게 아니라 node_modules의 @types 폴더를 잡는 문제)
때문에 customTypes 라는 폴더를 만들어서 사용하면 어떨까 합니다!

2024-01-31 14:16 UTC, dongkyun-dev commented
@dmswl98 
도커 빌드를 위해서 `.env.production` 파일은 노출이 필요합니다. `.env.local` 파일의 경우 중요한 내용이 담긴다면 숨겨야겠지만 지금으로써는 크게 숨길 내용이 존재하지 않아 그대로 올려두었습니다!

2024-01-31 14:16 UTC, dongkyun-dev commented on src/components/Layout/components/Header.tsx
> +
리뷰 감사합니다! 반영해보았습니다 ㅎㅎ

2024-01-31 14:17 UTC, dongkyun-dev commented on src/api/auth.ts
> +      `https://dev.api.ba-ro.co.kr/auth/oauth/sign-in/${authType}?authCode=${code}`,
env를 사용하는 형태로 변경해보았습니다!
미들웨어에서 axios 사용이 안돼서 fetch를 불가피하게 사용하였습니다!

2024-01-31 14:17 UTC, dongkyun-dev commented on middleware.ts
> +    const response = NextResponse.redirect(new URL('/write', request.url));
그게 좋겟네요 ㅎㅎ 해당 부분 반영해보았습니다.

2024-02-02 11:04 UTC, dmswl98 commented on src/stores/token.ts
> +}
그렇군요... 1번 방법보다는 2번 방법이 더 좋은 듯해요!
그럼 middleware을 사용하신 이유는 무엇인가요?!?

2024-02-02 11:08 UTC, dmswl98 approved these changes
너무 늦게 확인했네요ㅜㅜ 수고하셨습니다!!

2024-02-02 11:08 UTC, dmswl98 commented on src/components/Modal/modals/Login.tsx
> +  const onClickSocialLogin = (type: OAuthType) => async () => {
컴포넌트 내부 이벤트 핸들러는 handle + 명사 + 동사, 
핸들러를 prop으로 넘기는 경우에는 on + 동사 + 명사로 맞추면 좋을 것 같아요!

2024-02-03 03:12 UTC, dongkyun-dev commented on src/stores/token.ts
> +}
@dmswl98 
요거 오늘 만나서 한번 이야기해봐도 좋을 것 같아요!!

2024-02-05 11:37 UTC, dongkyun-dev commented on src/components/Modal/modals/Login.tsx
> +  const onClickSocialLogin = (type: OAuthType) => async () => {
@dmswl98 
말씀주신 부분들 반영해보았습니다! 감사합니다 ㅎㅎ

2024-02-05 11:38 UTC, dmswl98 commented on src/components/Modal/modals/Login.tsx
> +  const onClickSocialLogin = (type: OAuthType) => async () => {
👍🏻 머지 고고~

2024-02-06 03:27 UTC, merged